### ISSUE TITLE
Update on PyPI

### ISSUE THREAD

**Issue by phw** [metabrainz/liblistenbrainz#24]
Update this package on https://pypi.org/project/pylistenbrainz/

**Comment by georgkrause** [comment]
I just found this issue. I started working on automating the updating in https://github.com/metabrainz/pylistenbrainz/pull/26

However, as far as I am aware there are some issues regarding the ownership that needs to be resolved first.

**Comment by georgkrause** [comment]
Alright, so since the access to the account managing the package on pypi got lost, I discusses with @mayhem if its feasible to rename the package. I think the least controversial suggestion have been `pylistenbrainz`, however this is open for discussion.

Renaming has some obvious disadvantages:

- Users probably need to update their code to adjust the package name
- Users of this package might don't notice there was a name change and don't receive expected updates anymore

This is what comes to my mind. I don't know who the responsible parties are, just let me know what you think!

**Comment by georgkrause** [comment]
@mayhem We could do a pre-release to test the pipeline and do a proper release afterwards so everyone can update the dependency. What do you think?

**Comment by georgkrause** [comment]
@phw Just a notice for you as author, `pylistenbrainz` is dead, the new package will be named `liblistenbrainz`

**Comment by mayhem** [comment]
Just started with the pre-release --- lets see how it goes.

**Comment by mayhem** [comment]
It failed -- are you able to see the results? How do we add the needed tokens?

**Comment by phw** [comment]
@mayhem in pypi.org go to https://pypi.org/manage/project/liblistenbrainz/settings/publishing/ and add a new trusted publisher.

Repository: metabrainz/liblistenbrainz  
Workflow: cd.yml
Environment name: *can I think be left empty for the current setup*

Not sure what would happen if the project does not yet exist on pypi, though. Might be this would need a manual publishing the very first time.

**Comment by phw** [comment]
@mayhem Should work without project also, on https://pypi.org/manage/account/publishing/

**Comment by georgkrause** [comment]
> Not sure what would happen if the project does not yet exist on pypi, though.

Just for completeness, the project would be created then. No manual intervention required

**Comment by phw** [comment]
https://pypi.org/project/liblistenbrainz/
